openapi: 3.0.0
info:
  title: PDFreactor Web Service Monitoring REST API
  description: >
    This is the monitoring REST API definition and documentation of the PDFreactor Web Service.
    To use the monitoring API, an adminKey has to be configured on the server.
  termsOfService: https://www.pdfreactor.com
  contact:
    name: PDFreactor Support Team
    email: support@realobjects.com
    url: http://www.pdfreactor.com
  license:
    name: PDFreactor Software License Agreement
    url: https://www.pdfreactor.com
  x-logo:
    url: https://www.realobjects.com/wp-content/uploads/images/logos/prlogo-180x180.png
    altText: PDFreactor Logo
  version: 10.1.10722.9

servers:
  - url: http://localhost:9423/service/monitor
paths:
  /server:
    get:
      description: Retrieves information about the PDFreactor Web Service that is currently running.
      summary: Service information
      parameters:
        - &adminKey
          in: query
          name: adminKey
          schema:
            type: string
          description: >
            The admin key to authenticate the request.
      responses:
        '200':
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationInfo'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApplicationInfo'
        '401': &response401
          description: The client failed an authorization check, e.g. because a supplied admin key was invalid.
        '503': &response503
          description: The PDFreactor Web Service is not available.
  /conversions:
    get:
      description: Retrieves information about the conversions on the server.
      summary: Conversion information
      parameters:
        - *adminKey
      responses:
        '200':
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversionInfoContainer'
            application/xml:
              schema:
                $ref: '#/components/schemas/ConversionInfoContainer'
        '401': *response401
        '503': *response503
  /conversions/running:
    get:
      description: Retrieves information about the running conversions on the server.
      summary: Running conversion information
      parameters:
        - *adminKey
      responses: &conversionInfo
        '200':
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversionInfo'
            application/xml:
              schema:
                $ref: '#/components/schemas/ConversionInfo'
        '401': *response401
        '503': *response503
  /conversions/queued:
    get:
      description: Retrieves information about the queued conversions on the server.
      summary: Queued conversion information
      parameters:
        - *adminKey
      responses: *conversionInfo
  /conversions/finished:
    get:
      description: Retrieves information about the finished conversions on the server.
      summary: Running conversion information
      parameters:
        - *adminKey
      responses: &conversionAmount
        '200':
          description: Operation successful
          content:
            text/plain:
              schema:
                type: number
                minimum: 0
        '401': *response401
        '503': *response503
  /conversions/finished/successful:
    get:
      description: Retrieves information about the successfully finished conversions on the server.
      summary: Successful conversion information
      parameters:
        - *adminKey
      responses: *conversionAmount
  /conversions/finished/failed:
    get:
      description: Retrieves information about the erroneously finished conversions on the server.
      summary: Failed conversion information
      parameters:
        - *adminKey
      responses: *conversionAmount
components:
  schemas:
    ApplicationInfo:
      properties:
        name:
          type: string
          description: The name of the RealObjects Web Service. In the case of a PDFreactor Web Service, this will always be 'PDFreactor Web Service'.
        id:
          type: string
          description: The ID of the PDFreactor Web Service instance.
        state:
          type: string
          description: The current state of the service.
        server:
          allOf:
            - $ref: '#/components/schemas/ServerInfo'
          description: Information about the server the service is running on.
        plugins:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/PluginInfo'
          description: The plugins that are registered for the service
        parameters:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/ServerParameterInfo'
          description: All server parameters and how they are configured.
        version:
          allOf:
            - $ref: '#/components/schemas/Version'
          description: The version of the service.
        date:
          type: string
          format: date-time
          description: The date since the service is running.
        supportsRestart:
          type: boolean
          description: Whether the service supports being restarted.
    Conversion:
      properties:
        contentType:
          type: string
          description: The content type of the converted document.
        conversionTime:
          type: integer
          format: int64
          description: The total conversion time in milliseconds.
        endData:
          type: string
          format: date-time
          description: The date and time when this conversion was finished.
        error:
          type: string
          description: An error message if the conversion finished unsucessfully.
        id: 
          type: string
          description: The ID of the converted document.
        numberOfPages:
          type: integer
          description: The number of document pages, ignoring generated pages such as the log. 
        numberOfPagesLiteral:
          type: integer
          description: The number of actual document pages.
        requestDate:
          type: string
          format: date-time
          description: The date and time when this conversion was requested.
        size:
          type: array
          items: 
            type: integer
            format: int64
          description: The size in bytes of the resulting document or each page of a multi-image.
        startDate:
          type: string
          format: date-time
          description: The date and time when this conversion was started.
        succes:
          type: boolean
          description: Whether the conversion finished successfully.
        sync:
          type: boolean
          description: Whether this conversion was triggered synchronously.
    ConversionInfo:
      properties:
        amount:
          type: integer
          description: The amount of conversions.
        conversions:
          type: array
          items:
            $ref: '#/components/schemas/Conversion'
          description: The conversions.
        serviceId:
          type: string
          description: The ID of the PDFreactor Web Service instance.
    ConversionInfoContainer:
      properties:
        failedConversions:
          type: integer
          description: The amount of failed conversions.
        finishedConversions:
          type: integer
          description: The amount of finished conversions.
        queuedConversions:
          allOf:
            - $ref: '#/components/schemas/ConversionInfo'
          description: The currently queued conversions.
        runningConversions:
          allOf:
            - $ref: '#/components/schemas/ConversionInfo'
          description: The currently running conversions.
        serviceId:
          type: string
          description: The ID of the PDFreactor Web Service instance.
    PluginInfo:
      properties:
        id:
          type: string
          description: The ID of the plugin.
        version:
          type: string
          description: The version of the plugin.
        vendor:
          type: string
          description: The vendor of the plugin.
        type:
          type: string
          description: The type of the plugin.
        interface:
          type: string
          description: the interface of the plugin.
        used:
          type: boolean
          description: Whether or not the plugin is currently in use.
    ServerInfo:
      properties:
        availableMemory:
          type: number
          format: int
          description: The amount of memory currently available to Java.
        dockerLabel:
          type: string
          description: The label of the docker container, if applicable.
        environmentVariables:
          type: object
          additionalProperties:
            type: string
          description: The environment variables configured on the server.
        maxMemory:
          type: number
          format: int64
          description: The maximum amount of memory available to Java.
        numberOfCpuCores:
          type: integer
          description: The amount of CPU cores that was detected by Java.
        systemProperties:
          type: object
          additionalProperties:
            type: string
          description: The Java system properties configured for the Java VM.
        usedMemory:
          type: number
          format: int64
          description: The amount of memory currently used by Java.
    ServerParameterInfo:
      properties:
        name:
          type: string
          description: The name of the server parameter.
        value:
          type: string
          description: The value of the server parameter. Only applicable for scalar parameters.
        values:
          type: array
          items:
            type: string
          description: An array of values of the server parameter. Only applicable for array-type parameters.
    Version:
      properties:
        build:
          type: integer
          description: >
            The build number.
        label:
          type: string
          description: >
            The label of the version.
        major:
          type: integer
          description: >
            The major version.
        micro:
          type: integer
          description: >
            The micro version.
        minor:
          type: integer
          description: >
            The minor version.
        revision:
          type: string
          description: >
            The revision number.